task-manager/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks
end

task-manager/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task-manager/app/models/task.rb
class Task < ApplicationRecord
end

task-manager/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

task-manager/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end
  def show
    @task = Task.find(params[:id])
  end
  def new
  end
  def create
  end
  def edit
  end
  def update
  end
  def destroy
  end
end

task-manager/app/helpers/application_helper.rb
module ApplicationHelper
end

task-manager/app/helpers/tasks_helper.rb
module TasksHelper
end

task-manager/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

task-manager/app/views/tasks/index.html.erb
<h1>Les taches à effectuer</h1>

<% @tasks.each do |task| %>
 <h2> <%= task.name %></h2>
 <%= link_to "Voir la tache", task_path(task) %>



  <% end %>

task-manager/app/views/tasks/show.html.erb
<h1><%= @task.name %> </h1>

<%= link_to "Retour aux taches", tasks_path %>